### ISSUE TITLE
Multiple language output.

### ISSUE THREAD

**Issue by V1Htor** [YusufOzmen01/kikitan-translator#2]
I'd ask for a feature to add additional languages to output. Sometimes chatting in a group with multiple asians requires constant switch between languages.

**Comment by YusufOzmen01** [comment]
The limiting factor here is currently the maximum characters the chatbox allows. So, adding multiple outputs is going to fill the chatbox really quickly. I will look into it but cannot guarantee that I will be able to do it.

**Comment by V1Htor** [comment]
> The limiting factor here is currently the maximum characters the chatbox allows. So, adding multiple outputs is going to fill the chatbox really quickly. I will look into it but cannot guarantee that I will be able to do it.

Oh, for real. Thank you for looking into this. Maybe add an option to disable, for example, the showcase of original language? And adding some kind of a meter that says when the message is too long (So you could calibrate your mind;saying to fit in limited length). I remember having problems with long sentences, yes.
