### ISSUE TITLE
Mute syncronization with VRChat

### ISSUE THREAD

**Issue by TheXev** [YusufOzmen01/kikitan-translator#3]
I love Kikitan translator, and would love to see a mute synchronization feature added.  Via OSC, it should be possible for Kikitan to read the mute status of VRChat, and stop transcription during mute. I would still provide a toggle to turn the feature on and off, as sometimes it's good to turn it off, but other times you might want it on. It is a great feature to have for when you need to mute and speak with a family member or take a phone call, and you don't want to transcribe those conversations.

**Comment by YusufOzmen01** [comment]
Had this in my mind for a while but I was too busy with life and school so didn't work on it yet. I'll look into it soon!
