### ISSUE TITLE
Stop button

### ISSUE THREAD

**Issue by linkdmw** [YusufOzmen01/kikitan-translator#5]
I suggest adding a Stop/Continue button to the interface, so that we can use the OVR Toolkit/OVR advance setting in the game to quickly stop and resume kikitan's work, rather than completely shut it down.
Finally thank you for your contribution, it was a very helpful project!

**Comment by YusufOzmen01** [comment]
Sorry for being late, I wasn't checking GitHub for a while now. 

You can use the VRChat OSC switch on the top bar to Disable/Enable Kikitan. Detections continue to work but translations stop and the output doesn't get sent to the in game chatbox!

I will most likely do a UI overhaul to make some things more easier to understand soon!
