### ISSUE TITLE
Sound I/O settings, OCR, and logs

### ISSUE THREAD

**Issue by LemonAdorable** [YusufOzmen01/kikitan-translator#7]
Currently the program appears as Microsoft Edge WebView 2 in the volume synthesizer, and if I need this plugin to translate someone else's voice, then I need a virtual sound card. However, changes to the above program often didn't work in the system volume synthesizer, and I had to change the default I/O configuration for the entire system and adjust the virtual sound card accordingly. I would like to be able to modify the input and output of the software's sound, or I would like the software to provide a solution that doesn't require a virtual sound card, but if I use this solution, I want the software not to intercept the sound of the entire system, but to choose to intercept a specific device or program.

If this function is realized, I think it will be easy to realize the function of simultaneous interpretation. One of the simplest ideas is to have the translator user turn down the other person's voice so that they can hear the voice provided by the translator.

Although the recognition is not very accurate at present, the simultaneous interpretation function may be more limited. But since the software only calls the interface, it may soon have a practical use.

In addition, I hope to add an OCR translation service interface that can modify shortcut keys, providing the function of pressing shortcut keys to translate and continuously translate text.

Since the translation speed may be too fast in the actual scenario, perhaps adding a log to store all recent translations and make them easy for the user to view can solve this problem.

In this way, the software can be adapted to almost any scenario that requires translation with a simple setup and a small amount of resources

**Comment by YusufOzmen01** [comment]
First, I cannot change which device is being used for Web Speech API. It always uses the default microphone. I would add an option if it was supported. Second, Kikitan's current purpose is not to translate other people's voices, but your own. Current structure of the program is made for that purpose and using workarounds like virtual sound cards are, well, workarounds. And I cannot really support translating other people's voices at the moment as like I said, it's not the purpose of Kikitan. But soon, I am planning on getting rid of Web Speech API and utilizing whisper.cpp if I can make it performant enough. After that implementation, translating other people's voices is something that I can approach to.

But in a nutshell, current state of Kikitan doesn't really allow me to reliably translate other people's voices.

I did not understand what you meant by "OCR translation service". Object Character Recognition? That is not really what Kikitan is designed for. Can you elaborate on what you said?

A translation log seems like a good idea though, I'll add it to my notes, thank you!

If you can elaborate on your ideas a bit more after reading my message, I'd be happy! And sorry for responding late, I don't check GitHub often.

**Comment by LemonAdorable** [comment]
Sorry, I misinterpreted the first sentence of the readme file. My idea was that only one of the talkers needs to have kikitan to achieve mutual understanding. That's all.
What I meant by using OCR translation is that there are times when I need to translate text sent from someone else's chatbox, and that usually applies to people who can't open a mic.
I hope you can do better when you change your implementation. Simultaneous translation with just one person having the software is just a vision I had. Thank you for your reply.

**Comment by YusufOzmen01** [comment]
Oh, okay I understand now. The OCR translation is probably better to be utilized with another application as that will overcomplicate Kikitan and stray away from it's reason of existence. But, translating other people's voices is something I have in my mind and looking into. I am closing this issue for now but when I start working on simultaneous translation, I will let you know.
